name: Generate changelog

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate changelog
        uses: saadmk11/changelog-ci@master
        with:
          config_file: changelog-ci-config.json
