name: Generate changelog

on:
  pull_request:
    branches:
      - master
    types: [opened, reopened]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generate changelog
        uses: saadmk11/changelog-ci@v0.7.0
        with:
          config_file: changelog-ci-config.json
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
