name: Publish to NPM & GPR

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        os: [ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn --check-files --frozen-lockfile --non-interactive

      - name: Build project
        run: yarn run build

      - name: Run unit tests
        run: yarn test

  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        os: [ubuntu-latest]
        npm: 'https://registry.npmjs.org'
        gpr: 'https://npm.pkg.github.com'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: ${{ matrix.npm }}

      - name: Install dependencies
        run: yarn --check-files --frozen-lockfile --non-interactive

      - name: Publish to NPM registry
        run: yarn publish

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: ${{ matrix.gpr }}

      - name: Publish to Github packages registry
        run: yarn publish

        env:
          NODE_AUTH_TOKEN: ${{ secrets.GPR_TOKEN }}

    needs: build
